### ISSUE TITLE
additional extrusion on generated *.stl

### ISSUE THREAD

**Issue by sugizo** [niljub/pic2stl#2]
**image**
![image](https://github.com/niljub/pic2stl/assets/2418295/4005c29a-a599-45ab-b3bc-bb00a4fffa02)

**code**
```
file_name = 'batman
image_to_stl('%s_ori.png' % file_name, '%s_0.stl' % file_name, extrusion_height = 3, add_base = False)
image_to_stl('%s_ori.png' % file_name, '%s_1.stl' % file_name, extrusion_height = 3, add_base = True, base_thickness = 0)
```

**result**
![image](https://github.com/niljub/pic2stl/assets/2418295/32e77854-d0a9-4db2-b1b3-a5cf1072e726)

**expected result**
no additional extrusion, for example above is seen on bottom left

**p.s.**
try add_base (True and False), 
also have the additional extrusion on bottom left

best regards

**Comment by niljub** [comment]
The extra extrusion on the bottom left corner of the generated STL file is created due to an the "tm" watermark present in the lower right corner of the input image. Removing or cropping out this watermark from the image before processing it should resolve the issue.

**Comment by niljub** [comment]
The extra extrusion on the bottom left corner of the generated STL file is due to the "tm" watermark present in the lower right corner of the input image. Removing or cropping out this watermark from the image before processing it will resolve the issue.
