### ISSUE TITLE
invert feature

### ISSUE THREAD

**Issue by sugizo** [niljub/pic2stl#3]
nice to have invert feature with
True or False value

e.g.
invert : True (1)
![image](https://github.com/niljub/pic2stl/assets/2418295/a37e3e41-10de-441a-9643-cf359c41c67a)

invert : False (0)
![image](https://github.com/niljub/pic2stl/assets/2418295/a52feb01-fdc3-41fc-b619-91695481f896)

best regards

**Comment by niljub** [comment]
Invert feature has been added with the latest version, the argument is called `invert_image` and is set to `False` by default

**Comment by niljub** [comment]
Invert feature has been added with the latest version, the argument is called `invert_image` and is set to `False` by default
