### ISSUE TITLE
scale feature

### ISSUE THREAD

**Issue by sugizo** [niljub/pic2stl#4]
nice to have scale feature
so that user can set the scale for :
x (length), y (width) or z (height extrusion)

![image](https://github.com/niljub/pic2stl/assets/2418295/bd02a466-dcfa-4f5f-a59a-336de98904e7)

**Comment by niljub** [comment]
Could you please elaborate on why it's beneficial to have a scaling feature within the tool? Usually this can be done with the slicer.
