### ISSUE TITLE
rotate feature

### ISSUE THREAD

**Issue by sugizo** [niljub/pic2stl#5]
nice to have rotate feature
so that the output (*.stl) can be either lay down (horizontal)
or
straight up (vertical)
in x, y, z value

e.g.
![image](https://github.com/niljub/pic2stl/assets/2418295/c0f0cf57-3f30-4b2b-8028-fe1db16600eb)

**Comment by niljub** [comment]
Just like with the scaling feature, it's hard to see any reasons not to utilize the slicer. Could you elaborate?
